server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/file_server_db
    username: admin
    password: admin
  liquibase:
    url: jdbc:mysql://localhost:3306/file_server_db
    user: admin
    password: admin
    change-log: db/changelog/db.changelog-master.yaml
  security:
    token:
      ttl-in-minutes: 30
      secret-key: R2xCYWZDMURId2NqM1V0NWVMeE15SXp2aENEZE1RMEsrTDR1ZTR0MGdnWXZaZDNJV09PZERFUDFHaG1BclYwWQ==
aws:
  access-key-id: XXXXXXXXXXXXXXX
  secret-access-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  region: ru-central1
  s3-bucket-name: webflux-fileserver
  s3-endpoint: https://storage.yandexcloud.net
  multipart-min-part-size: 5242880





